### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by toyxyz** [xyfJASON/ctrlora#8]
When I ran the example training script, I got the following error 

```
HPU available: False, using: 0 HPUs
C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W socket.cpp:663] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:7250 (system error: 10049 - The requested address is not valid in that context.).
Traceback (most recent call last):
  File "C:\Users\toyxy\ctrlora\scripts\train_ctrlora_finetune.py", line 130, in <module>
    trainer.fit(model, dataloader)
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\pytorch_lightning\trainer\call.py", line 46, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 937, in _run
    self.strategy.setup_environment()
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\lightning_fabric\utilities\distributed.py", line 297, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\torch\distributed\distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "C:\Users\toyxy\.conda\envs\ctrlora\lib\site-packages\torch\distributed\distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
```

**Comment by scarbain** [comment]
Had the same issue. Gave the script + error to o1-mini and it fixed the error with the following script (to replace ./scripts/train_ctrlora_finetune.py) :

`import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from share import *

import gc
import argparse
import datetime

import torch
import pytorch_lightning as pl
from torch.utils.data import DataLoader, Subset

from datasets.multigen20m import MultiGen20M
from datasets.custom_dataset import CustomDataset
from cldm.logger import ImageLogger, CheckpointEveryNSteps
from cldm.model import create_model, load_state_dict
from cldm.hack import enable_sliced_attention


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="args")
    # Dataset configs
    parser.add_argument("--dataroot", type=str, required=True, help='path to dataset')
    parser.add_argument("--drop_rate", type=float, default=0.3, help='drop rate for classifier-free guidance')
    parser.add_argument("--multigen20m", action='store_true', default=False, help='use multigen20m dataset')
    parser.add_argument("--task", type=str, choices=[
        'hed', 'canny', 'seg', 'depth', 'normal', 'openpose', 'hedsketch',
        'bbox', 'outpainting', 'inpainting', 'blur', 'grayscale',
    ], help='task name')
    parser.add_argument("--subset", type=int, default=0, help='train on a subset of the dataset')
    # Model configs
    parser.add_argument("--config", type=str, required=True, help='path to model config file')
    parser.add_argument("--sd_ckpt", type=str, required=True, help='path to pretrained stable diffusion checkpoint')
    parser.add_argument("--cn_ckpt", type=str, required=True, help='path to pretrained controlnet checkpoint')
    # Training configs
    parser.add_argument("-n", "--name", type=str, help='experiment name')
    parser.add_argument("--lr", type=float, default=1e-5, help='learning rate')
    parser.add_argument("--bs", type=int, default=1, help='batchsize per device')
    parser.add_argument("--max_steps", type=int, default=100000, help='max training steps')
    parser.add_argument("--gradacc", type=int, default=1, help='gradient accumulation')
    parser.add_argument("--precision", type=int, default=32, help='precision')
    parser.add_argument("--save_memory", action='store_true', default=False, help='save memory using sliced attention')
    parser.add_argument("--img_logger_freq", type=int, default=1000, help='img logger freq')
    parser.add_argument("--ckpt_logger_freq", type=int, default=1000, help='ckpt logger freq')
    args = parser.parse_args()

    # Save memory
    if args.save_memory:
        enable_sliced_attention()

    # Construct Dataset
    if args.multigen20m:
        dataset = MultiGen20M(
            path_json=os.path.join(args.dataroot, 'json_files', f'aesthetics_plus_all_group_{args.task}_all.json'),
            path_meta=args.dataroot, task=args.task, drop_rate=args.drop_rate,
        )
    else:
        dataset = CustomDataset(args.dataroot, drop_rate=args.drop_rate)
    if args.subset > 0:
        dataset = Subset(dataset, range(args.subset))
    dataloader = DataLoader(dataset, num_workers=16, batch_size=args.bs, shuffle=True)
    print('Dataset size:', len(dataset))
    print('Number of devices:', torch.cuda.device_count())
    print('Batch size per device:', args.bs)
    print('Gradient accumulation:', args.gradacc)
    print('Total batch size:', args.bs * torch.cuda.device_count() * args.gradacc)

    # Construct Model
    model = create_model(args.config).cpu()
    model.learning_rate = args.lr
    model.sd_locked = True
    model.only_mid_control = False

    scratch_dict = model.state_dict()

    # Copy Stable Diffusion weights to scratch_dict
    copied_keys, missing_keys = [], []
    sd_weights = load_state_dict(args.sd_ckpt, location='cpu')
    for k in sd_weights:
        if k not in scratch_dict:
            missing_keys.append(k)
        else:
            scratch_dict[k] = sd_weights[k].clone()
            copied_keys.append(k)
    os.makedirs('./tmp', exist_ok=True)
    with open('./tmp/finetune_missing_keys_sd.txt', 'w') as f:
        f.write('\n'.join(missing_keys))
    with open('./tmp/finetune_copied_keys_sd.txt', 'w') as f:
        f.write('\n'.join(copied_keys))

    # Copy ControlNet weights to scratch_dict
    copied_keys, missing_keys = [], []
    control_weights = load_state_dict(args.cn_ckpt, location='cpu')
    for k in control_weights:
        if 'control_model' in k:
            if k not in scratch_dict:
                missing_keys.append(k)
            elif 'lora' in k:
                pass
            else:
                scratch_dict[k] = control_weights[k].clone()
                copied_keys.append(k)
    with open('./tmp/finetune_missing_keys_cn.txt', 'w') as f:
        f.write('\n'.join(missing_keys))
    with open('./tmp/finetune_copied_keys_cn.txt', 'w') as f:
        f.write('\n'.join(copied_keys))

    # Load scratch_dict to model
    model.load_state_dict(scratch_dict, strict=True)
    print(f"Successfully initialize SD from {args.sd_ckpt}")
    print(f"Successfully initialize ControlNet from {args.cn_ckpt}")
    del sd_weights, control_weights, scratch_dict
    gc.collect()

    # Determine the number of available GPUs
    num_gpus = torch.cuda.device_count()

    # Ensure at least one GPU is available
    if num_gpus < 1:
        raise ValueError("No GPUs detected. Please ensure that a GPU is available and properly configured.")

    # Build Trainer without specifying the strategy
    logger_img = ImageLogger(batch_frequency=args.img_logger_freq)
    logger_checkpoint = CheckpointEveryNSteps(save_step_frequency=args.ckpt_logger_freq)
    if args.name is None:
        args.name = datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
    trainer = pl.Trainer(
        accelerator='gpu',
        devices=1,  # Use only one GPU
        accumulate_grad_batches=args.gradacc,
        max_steps=args.max_steps,
        precision=args.precision,
        callbacks=[logger_img, logger_checkpoint],
        default_root_dir=os.path.join("U:/Flaash/Watermark_removal/CTRLORA", args.name),
    )

    # Train!
    trainer.fit(model, dataloader)
`

**Comment by toyxyz** [comment]
I got another error, and changed the following code 

`TypeError: LatentDiffusion.on_train_batch_start() missing 1 required positional argument: 'dataloader_idx'
`
https://github.com/xyfJASON/ctrlora/blob/177e51453f25a96fd7fa91ac361e276134f6df37/ldm/models/diffusion/ddpm.py#L591

to `def on_train_batch_start(self, batch, batch_idx): `

**Comment by toyxyz** [comment]
> Had the same issue. Gave the script + error to o1-mini and it fixed the error with the following script (to replace ./scripts/train_ctrlora_finetune.py) : https://pastebin.com/qQGWq7qx

Thank you! 

I needed to modify the following code 

`default_root_dir=os.path.join("U:/Flaash/Watermark_removal/CTRLORA", args.name),`

to `default_root_dir=os.path.join('runs', args.name),`
